user_new:
    path: /new
    defaults: { _controller: "AppBundle:Task:new" }
    methods: POST

user_edit:
    path: /edit/{id}
    defaults: { _controller: "AppBundle:Task:new", id:null }
    methods: POST